# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BankChallengeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BankChallengeApp

  pod 'SwiftLint'
  pod 'SnapshotTesting', '~> 1.9.0'

  target 'BankChallengeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BankChallengeAppUITests' do
    # Pods for testing
  end

end
